name: object_detector
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #state management
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  #data class generation
  freezed_annotation: ^2.1.0
  #dependency injection
  get_it: ^7.2.0
  #ui
  percent_indicator: ^4.2.2
  #utility
  image_picker: ^0.8.6
  google_mlkit_image_labeling: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  #linter
  flutter_lints: ^2.0.0
  #code generation
  freezed: ^2.1.0+1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
